#!/usr/bin/env bash
# macOS 09-game-servers.sh — load extra pf rules for game/voice servers.
# Auto-detects which ports are listening before adding rules.
set -euo pipefail
source "${DDOS_SCRIPT_DIR}/lib/ui.sh"

ANCHOR=/etc/pf.anchors/ddos-protect-games
RULES=""

add_udp() {
    local port="$1" rate="$2" label="$3"
    RULES+=$'\n'"# $label
pass in quick proto udp from any to any port $port keep state \
    (max-src-conn-rate $rate/5, overload <bruteforce>)"
}
add_tcp() {
    local port="$1" rate="$2" label="$3"
    RULES+=$'\n'"# $label
pass in quick proto tcp from any to any port $port flags S/SA keep state \
    (max-src-conn 30, max-src-conn-rate $rate/10, overload <bruteforce> flush global)"
}

listening_udp="$(netstat -anu 2>/dev/null | awk '/^udp/ {print $4}' | awk -F. '{print $NF}' | sort -u)"
listening_tcp="$(netstat -antu 2>/dev/null | awk '/^tcp/ && /LISTEN/ {print $4}' | awk -F. '{print $NF}' | sort -u)"

is_udp() { grep -qw "$1" <<<"$listening_udp"; }
is_tcp() { grep -qw "$1" <<<"$listening_tcp"; }

is_tcp 25565 && add_tcp 25565 5  "Minecraft Java"
is_udp 19132 && add_udp 19132 60 "Minecraft Bedrock"
is_udp 30120 && add_udp 30120 120 "FiveM"
is_udp 9987  && add_udp 9987  80 "TeamSpeak3 voice"
is_tcp 10011 && add_tcp 10011 2  "TeamSpeak3 query"
is_tcp 30033 && add_tcp 30033 5  "TeamSpeak3 file"
is_udp 64738 && add_udp 64738 80 "Mumble"
is_udp 27015 && add_udp 27015 50 "Source engine"

if [[ -z "$RULES" ]]; then
    note "No known game/voice ports detected — skipping."
    exit 0
fi

cat > "$ANCHOR" <<EOF
# Game-server protections — generated by 09-game-servers.sh
$RULES
EOF

if ! grep -q ddos-protect-games /etc/pf.conf; then
    cat >> /etc/pf.conf <<HOOK
anchor "ddos-protect-games"
load anchor "ddos-protect-games" from "$ANCHOR"
HOOK
fi

pfctl -nf /etc/pf.conf || { fail "pf syntax check failed"; exit 1; }
pfctl -f /etc/pf.conf
ok "Game-server pf rules applied"
